### ISSUE TITLE
No __main__.py

### ISSUE THREAD

**Issue by LossRP** [mikemaddem/BearCAD#3]
cannot start bearCAD, new to PHP downloaded requirements using git bash, cannot start bear CAD, in manage.py file it says to look for __manage__.py but there is none

**Comment by mikemaddem** [comment]
The only release for this project is unstable. Additionally the project isn't active, but when it is again, I'll be rewriting the entire thing with channels2

**Comment by LossRP** [comment]
sounds like a plan, are you open for donations to get the project moving?

**Comment by mikemaddem** [comment]
Maybe? Idk I don't wanna take someones money and make any promise that I'm not 110% sure I can commit to.

**Comment by LossRP** [comment]
Add me on discord, and we can figure something out. I am sick of people paying $$ for crappy CADs, If i could donate or help you in any way to get your project released so people have more options and something they could self host. It would benefit alot of people. 

OfficerScentral#9966

**Comment by mikemaddem** [comment]
closing this issue because of it's age and the fact the project was in a pre-release stage at the time and is currently being worked on again - check back for more soon.
// closed
